### ISSUE TITLE
Are you available to do some open source Rust project?

### ISSUE THREAD

**Issue by heyong4725** [Byron/byron#3]
Hi Sebastian,

You have done impressive Rust open source projects! I am wondering if you are available or interested to do other Rust projects?

(Sorry to reach out to you in this way since I do not use keybase apps).

Let me know how I can reach out to you to discuss more.

Thanks,
Yong

**Comment by Byron** [comment]
Hi Yong,

thanks for reaching out. The reason these OS-projects seem impressive is probably just due to the sheer amount of time and focus they receive. With that premise I think it's clear that I am not able to pick up anything else.

However, I might be able to to spare some time on a freelance basis if the work aligns with my skills and interests.

Cheers,
Sebastian

PS: If the OS project uses `gitoxide`, I am typically available for questions within a day if posted in the project's discussions.

**Comment by heyong4725** [comment]
Hi Sebastian,

The Rust project I mentioned is not OS project, it is https://github.com/dora-rs, a dataflow framework implemented using Rust language to power autonomous driving and robotic applications (e.g, dora-drives here). We are focusing on education and research domain. The main contributor is part-time, freelancer as well. 

Since majority of the collaborations are with teams in Xian, China, and I noticed you are currently based in Xian, that would be fantastic if you can do part-time, freelancer.

Cheers,
Yong

**Comment by Byron** [comment]
Hi Yong,

that seems interesting, even though it doesn't look like `git` is involved at all yet. If `gitoxide` would at some point be interesting to the project, my skillset might be useful some day, but without that it's too much of a digression from my current area of focus.

Please note that I am not Xi'an based anymore, but based in Berlin by now.

Cheers

**Comment by heyong4725** [comment]
Hi Sebastian,

Indeed, currently the git is not used. I am thinking of introducing GitOps to the project, such that all those dataflow operators (e.g., ML models) can be git managed, similar to Docker /DockerHub.

Anyway, thanks for quick response. We will keep following your gitoxide project.

Cheers,
Yong
